spring.application.name=safelogin-back

spring.datasource.url=jdbc:mysql://127.0.0.1:8889/safelogin
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 32+ chars required for HS256
app.jwt.secret=safelogin-super-secret-key-32chars-minimum-value
app.jwt.expiration-ms=86400000
